baseURL = "https://afrankie.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
# pagination = 10

title = "Afrankie"
author = "Afrankie"
copyright = ""

theme = "simpleness"
googleAnalytics = ""

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2021"
  showmonth = true
  slogan = "always make it happen"
  description = "A simple and concise hugo theme."
  disqus = ""

[params.valine]
  enable = false
  lang = 'en' # zh-CN
  appId = ''
  appKey = ''
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  enableHeaderVisitor = true
  debug = true

[params.utteranc]
  enable = true
  repo = "Afrankie/blog-comments" ##换成自己得
  issueTerm = "title"
  theme = "github-light"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[social]
  github = "https://github.com/Afrankie"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
